services:
  activemq:
    container_name: activemq_broker
    image: 'apache/activemq-classic:latest'
    ports:
      - '61616:61616'
      - '8161:8161'
  postgres:
    image: postgres:15
    container_name: order_service_db
    environment:
      POSTGRES_DB: Order_Service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
