services:
  activemq:
    image: 'apache/activemq-classic:latest'
    ports:
      - '61616'
  sqlserver:
    image: 'mcr.microsoft.com/azure-sql-edge:latest'
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - '1433:1433'
